name=miniMachineBLE
version=1.0.1
author=Henrique Aleixo <henrique.aleixo@trueiot.com.br>
maintainer=Henrique Aleixo <henrique.aleixo@trueiot.com.br>
sentence=Controle de robos miniMachine via Bluetooth Low Energy (BLE) com ESP32.
paragraph=Biblioteca para controlar robos miniMachine usando ESP32 e comunicacao BLE para movimento.
category=Device Control
url=https://github.com/CurtoLab/miniMachine.git
architectures=esp32
depends=NimBLE-Arduino,ArduinoJson
